[project]
name = "sparta-cat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hmmmm", email = "jinglin.he@edu.sait.ca" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "psycopg2>=2.9.12",
]

[project.scripts]
sparta-cat = "sparta_cat:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
